AllCops:
  TargetRubyVersion: 2.3.1
  Exclude:
    - 'spec/**/*'
  DisplayStyleGuide: true
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Metrics/LineLength:
  Max: 120
