require 'csv'
require 'date'
require 'pry'
require 'awesome_print'
require 'colorize'

require_relative 'scrap_movies/movie'
require_relative 'scrap_movies/classic_movie'
require_relative 'scrap_movies/modern_movie'
require_relative 'scrap_movies/ancient_movie'
require_relative 'scrap_movies/new_movie'
require_relative 'scrap_movies/movie_collection'
require_relative 'scrap_movies/netflix'
require_relative 'scrap_movies/theatre'
require_relative 'scrap_movies/cash_desk'
